sudo: false
language:
  - android
jdk:
  - oraclejdk8
before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-24
  - echo y|android update sdk --all --no-ui --force --filter android-24
script:
  - ./gradlew build jacocoTestReport --info --stacktrace
after_success:
  - bash <(curl -s https://codecov.io/bash)