sudo: false

language:
  - android

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter platform-tools
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-25.0.0
  - echo y|android update sdk --all --no-ui --force --filter android-25

script:
  - ./gradlew build jacocoTestReport --info --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/